-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_contracts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "contract_number" TEXT,
    "contract_title" TEXT NOT NULL,
    "contract_title_hindi" TEXT,
    "contract_type" TEXT NOT NULL,
    "language" TEXT NOT NULL DEFAULT 'ENGLISH',
    "description" TEXT,
    "description_hindi" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "builder_status" TEXT NOT NULL DEFAULT 'DRAFT',
    "current_step" INTEGER NOT NULL DEFAULT 1,
    "organization_id" TEXT NOT NULL,
    "created_by_id" TEXT NOT NULL,
    "assigned_to_id" TEXT,
    "buyer_name" TEXT NOT NULL,
    "buyer_gst_number" TEXT,
    "buyer_email" TEXT,
    "buyer_registered_address" TEXT,
    "buyer_contact_person" TEXT,
    "buyer_phone" TEXT,
    "supplier_name" TEXT,
    "supplier_email" TEXT,
    "supplier_phone" TEXT,
    "contract_value" REAL NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "advance_payment" REAL DEFAULT 0,
    "start_date" DATETIME NOT NULL,
    "end_date" DATETIME NOT NULL,
    "renewal_date" DATETIME,
    "is_import_contract" BOOLEAN NOT NULL DEFAULT false,
    "shared_contract_id" TEXT,
    "firm_name" TEXT,
    "gst_state" TEXT,
    "total_amount" REAL,
    "amount_in_words" TEXT,
    "shipping_terms" TEXT,
    "payment_terms" TEXT,
    "payment_period" TEXT,
    "payment_period_from" TEXT,
    "invoice_date" DATETIME,
    "negotiation_date" DATETIME,
    "latest_shipment_date" DATETIME,
    "acceptance_date" DATETIME,
    "bl_date" DATETIME,
    "lc_expiry_date" DATETIME,
    "lc_expiry_place" TEXT,
    "presentation_deadline" DATETIME,
    "advising_bank_name" TEXT,
    "advising_bank_city" TEXT,
    "advising_bank_pin" TEXT,
    "advising_bank_country" TEXT,
    "has_commercial_invoice" BOOLEAN NOT NULL DEFAULT false,
    "has_packing_list" BOOLEAN NOT NULL DEFAULT false,
    "has_bill_of_landing" BOOLEAN NOT NULL DEFAULT false,
    "has_certificate_of_origin" BOOLEAN NOT NULL DEFAULT false,
    "has_insurance_certificate" BOOLEAN NOT NULL DEFAULT false,
    "has_phytosanitary_certificate" BOOLEAN NOT NULL DEFAULT false,
    "documents_skipped" BOOLEAN NOT NULL DEFAULT false,
    "general_terms" TEXT,
    "general_terms_hindi" TEXT,
    "terms_and_clauses" TEXT,
    "terms_and_clauses_hindi" TEXT,
    "dispute_resolution_terms" TEXT,
    "agreement_checkbox" BOOLEAN NOT NULL DEFAULT false,
    "penalty_clause" TEXT,
    "governing_law" TEXT DEFAULT 'Indian Contract Act, 1872',
    "jurisdiction" TEXT DEFAULT 'India',
    "confidentiality_clause" BOOLEAN NOT NULL DEFAULT false,
    "force_majeure" BOOLEAN NOT NULL DEFAULT false,
    "risk_score" INTEGER NOT NULL DEFAULT 50,
    "risk_factors" TEXT,
    "industry" TEXT NOT NULL DEFAULT 'General',
    "risk_level" TEXT,
    "priority" TEXT NOT NULL DEFAULT 'medium',
    "tags" TEXT,
    "template_id" TEXT,
    "document_path" TEXT,
    "signed_document_path" TEXT,
    "is_signed" BOOLEAN NOT NULL DEFAULT false,
    "signed_date" DATETIME,
    "notice_period_days" INTEGER DEFAULT 30,
    "last_review_date" DATETIME,
    "next_review_date" DATETIME,
    "last_modified_by_id" TEXT,
    "notes" TEXT,
    "is_archived" BOOLEAN NOT NULL DEFAULT false,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    CONSTRAINT "contracts_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "contracts_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "contracts_assigned_to_id_fkey" FOREIGN KEY ("assigned_to_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "contracts_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "contract_templates" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_contracts" ("acceptance_date", "advance_payment", "advising_bank_city", "advising_bank_country", "advising_bank_name", "advising_bank_pin", "agreement_checkbox", "amount_in_words", "assigned_to_id", "bl_date", "builder_status", "buyer_contact_person", "buyer_email", "buyer_gst_number", "buyer_name", "buyer_phone", "buyer_registered_address", "confidentiality_clause", "contract_number", "contract_title", "contract_title_hindi", "contract_type", "contract_value", "created_at", "created_by_id", "currency", "current_step", "description", "description_hindi", "dispute_resolution_terms", "document_path", "end_date", "firm_name", "force_majeure", "general_terms", "general_terms_hindi", "governing_law", "gst_state", "has_bill_of_landing", "has_certificate_of_origin", "has_commercial_invoice", "has_insurance_certificate", "has_packing_list", "has_phytosanitary_certificate", "id", "industry", "invoice_date", "is_archived", "is_import_contract", "is_signed", "jurisdiction", "language", "last_modified_by_id", "last_review_date", "latest_shipment_date", "lc_expiry_date", "lc_expiry_place", "negotiation_date", "next_review_date", "notes", "notice_period_days", "organization_id", "payment_period", "payment_period_from", "payment_terms", "penalty_clause", "presentation_deadline", "priority", "renewal_date", "risk_factors", "risk_level", "risk_score", "shared_contract_id", "shipping_terms", "signed_date", "signed_document_path", "start_date", "status", "supplier_email", "supplier_name", "supplier_phone", "tags", "template_id", "terms_and_clauses", "terms_and_clauses_hindi", "total_amount", "updated_at") SELECT "acceptance_date", "advance_payment", "advising_bank_city", "advising_bank_country", "advising_bank_name", "advising_bank_pin", "agreement_checkbox", "amount_in_words", "assigned_to_id", "bl_date", "builder_status", "buyer_contact_person", "buyer_email", "buyer_gst_number", "buyer_name", "buyer_phone", "buyer_registered_address", "confidentiality_clause", "contract_number", "contract_title", "contract_title_hindi", "contract_type", "contract_value", "created_at", "created_by_id", "currency", "current_step", "description", "description_hindi", "dispute_resolution_terms", "document_path", "end_date", "firm_name", "force_majeure", "general_terms", "general_terms_hindi", "governing_law", "gst_state", "has_bill_of_landing", "has_certificate_of_origin", "has_commercial_invoice", "has_insurance_certificate", "has_packing_list", "has_phytosanitary_certificate", "id", "industry", "invoice_date", "is_archived", "is_import_contract", "is_signed", "jurisdiction", "language", "last_modified_by_id", "last_review_date", "latest_shipment_date", "lc_expiry_date", "lc_expiry_place", "negotiation_date", "next_review_date", "notes", "notice_period_days", "organization_id", "payment_period", "payment_period_from", "payment_terms", "penalty_clause", "presentation_deadline", "priority", "renewal_date", "risk_factors", "risk_level", "risk_score", "shared_contract_id", "shipping_terms", "signed_date", "signed_document_path", "start_date", "status", "supplier_email", "supplier_name", "supplier_phone", "tags", "template_id", "terms_and_clauses", "terms_and_clauses_hindi", "total_amount", "updated_at" FROM "contracts";
DROP TABLE "contracts";
ALTER TABLE "new_contracts" RENAME TO "contracts";
CREATE UNIQUE INDEX "contracts_contract_number_key" ON "contracts"("contract_number");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
